const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='foodie_pair_v1';
const defaultState={favorites:[],votes:{me:[],partner:[]},shopping:[],meals:[],person:'me'};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem(KEY)||'{}'));
let page='home',category='全部',query='',deferredPrompt=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const recipe=id=>RECIPES.find(r=>r.id===id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
const weekStart=()=>{const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d};
const recentIds=()=>state.meals.filter(m=>Date.now()-new Date(m.date).getTime()<7*864e5).map(m=>m.id);
function pickRandom(){const matches=state.votes.me.filter(x=>state.votes.partner.includes(x));const pool=matches.length?RECIPES.filter(r=>matches.includes(r.id)):RECIPES;const recent=recentIds();const weighted=pool.flatMap(r=>Array(recent.filter(x=>x===r.id).length?1:4).fill(r));return weighted[Math.floor(Math.random()*weighted.length)]}
function card(r){return `<article class="recipe-card" data-detail="${r.id}"><div class="food-art"><img src="${RECIPE_IMAGES[r.id]}" alt="${r.name}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="food-fallback" hidden>${r.emoji}</span><span class="menu-tag">${r.cat}</span><button class="fav-btn ${state.favorites.includes(r.id)?'on':''}" data-fav="${r.id}">${state.favorites.includes(r.id)?'♥':'♡'}</button></div><div class="card-body"><h3>${r.name}</h3><p>${r.desc}</p><div class="meta"><span>⏱ ${r.time}分钟</span><span>· ${r.difficulty}</span></div></div></article>`}
function home(){const suggestions=[...RECIPES].sort(()=>Math.random()-.5).slice(0,5);return `<section class="page"><div class="hero"><small>两个人的今日菜单</small><h2>今天吃点什么好？</h2><p>优先推荐双方都喜欢、最近没吃过的菜</p><button class="btn btn-light" data-random>帮我决定</button></div><div class="section-head"><h2>快捷入口</h2></div><div class="quick-grid"><button class="quick" data-go="vote"><b>💞</b><span>双人投票</span></button><button class="quick" data-cat="烤鱼"><b>🐟</b><span>烤鱼专区</span></button><button class="quick" data-go="shopping"><b>🛒</b><span>买菜清单</span></button></div><div class="section-head"><h2>为你推荐</h2><button class="text-btn" data-random>换一换</button></div><div class="card-scroll">${suggestions.map(card).join('')}</div><div class="section-head"><h2>最近吃过</h2><button class="text-btn" data-go="mine">全部记录</button></div>${state.meals.length?state.meals.slice(-2).reverse().map(mealRow).join(''):'<div class="list-card small">还没有记录，吃完一道菜后记得来打卡。</div>'}</section>`}
function recipesPage(){const cats=['全部','家常菜','烤鱼','火锅','汤羹','主食','泰餐','西餐','收藏'];let list=RECIPES.filter(r=>(category==='全部'||r.cat===category||(category==='收藏'&&state.favorites.includes(r.id)))&&r.name.includes(query));return `<section class="page"><label class="search">⌕<input id="searchInput" placeholder="搜索菜名" value="${esc(query)}"></label><div class="chips">${cats.map(c=>`<button class="chip ${category===c?'active':''}" data-category="${c}">${c}</button>`).join('')}</div><div class="recipe-list">${list.length?list.map(card).join(''):'<div class="empty" style="grid-column:1/-1"><b>🍽️</b>没有找到这道菜</div>'}</div></section>`}
function detail(id){const r=recipe(id);return `<section class="page"><button class="text-btn" data-back>‹ 返回菜谱</button><div class="detail-hero photo"><img src="${RECIPE_IMAGES[r.id]}" alt="${r.name}"><div class="detail-caption"><div class="detail-emoji">${r.emoji}</div><h2>${r.name}</h2><p>${r.desc}</p><div class="pills"><span class="pill">${r.cat}</span><span class="pill">⏱ ${r.time}分钟</span><span class="pill">${r.difficulty}</span></div></div></div><div class="detail-section"><h3>准备食材 · 2人份</h3>${r.ingredients.map(i=>`<div class="ingredient-row"><span>${i[0]}</span><b>${i[1]}</b></div>`).join('')}<button class="btn btn-soft btn-block" style="margin-top:12px" data-add-shop="${r.id}">一键加入买菜清单</button></div><div class="detail-section"><h3>详细步骤</h3><ol class="steps">${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div><button class="btn btn-primary btn-block" style="margin-top:14px" data-eaten="${r.id}">记录今天吃了这道菜</button></section>`}
function votePage(){const voted=state.votes[state.person],remaining=RECIPES.filter(r=>!voted.includes(r.id)&&!voted.includes('skip:'+r.id));const r=remaining[0];const matches=state.votes.me.filter(x=>!x.startsWith('skip:')&&state.votes.partner.includes(x));return `<section class="page vote-wrap"><div class="person-switch"><button data-person="me" class="${state.person==='me'?'active':''}">我的选择</button><button data-person="partner" class="${state.person==='partner'?'active':''}">搭子的选择</button></div>${matches.length?`<div class="match">🎉 已有 <b>${matches.length}</b> 道双方都喜欢，推荐时会优先出现</div>`:''}${r?`<div class="vote-card"><div class="vote-emoji">${r.emoji}</div><div class="small">${r.cat} · ${r.time}分钟</div><h2>${r.name}</h2><p class="small">${r.desc}</p><div class="vote-actions"><button class="nope" data-vote="no" data-id="${r.id}">跳过</button><button class="like" data-vote="yes" data-id="${r.id}">喜欢 ♡</button></div></div><p class="small">当前身份：${state.person==='me'?'我':'搭子'} · 已投 ${voted.length} 道</p>`:`<div class="empty"><b>🥳</b>这一轮投完啦<br><button class="btn btn-soft" style="margin-top:14px" data-reset-votes>重新投票</button></div>`}</section>`}
function shoppingPage(){const groups={};state.shopping.forEach((x,i)=>{(groups[x.cat]??=[]).push({...x,i})});return `<section class="page"><div class="row"><div class="grow"><h2 style="margin:4px 0">买菜清单</h2><p class="small">按食材类别自动整理</p></div>${state.shopping.length?'<button class="text-btn" data-clear-shop>清空</button>':''}</div>${state.shopping.length?Object.entries(groups).map(([g,items])=>`<div class="shopping-group"><h3>${g}</h3><div class="list-card">${items.map(x=>`<label class="check-row ${x.done?'done':''}"><input type="checkbox" data-check="${x.i}" ${x.done?'checked':''}><span class="grow">${x.name}</span><b>${x.amount}</b></label>`).join('')}</div></div>`).join(''):'<div class="empty"><b>🛒</b>清单还是空的<br><span class="small">打开菜谱，一键加入所需食材</span></div>'}</section>`}
function mealRow(m){const r=recipe(m.id);return `<div class="list-card row"><div style="font-size:34px">${r?.emoji||'🍽️'}</div><div class="grow"><h3>${r?.name||m.name}</h3><p class="small">${new Date(m.date).toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'})}</p></div><button class="text-btn" data-delete-meal="${m.uid}">删除</button></div>`}
function minePage(){const favs=RECIPES.filter(r=>state.favorites.includes(r.id));const week=state.meals.filter(m=>new Date(m.date)>=weekStart());const counts={};week.forEach(m=>{const c=recipe(m.id)?.cat||'其他';counts[c]=(counts[c]||0)+1});const max=Math.max(1,...Object.values(counts));return `<section class="page"><div class="summary-grid"><div class="stat"><b>${favs.length}</b><span>我的收藏</span></div><div class="stat"><b>${week.length}</b><span>本周用餐</span></div><div class="stat"><b>${new Set(week.map(x=>x.id)).size}</b><span>不同菜品</span></div></div><div class="section-head"><h2>本周统计</h2></div><div class="list-card">${Object.keys(counts).length?Object.entries(counts).map(([c,n])=>`<div class="bar-row"><span>${c}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join(''):'<p class="small">本周还没有用餐记录。</p>'}</div><div class="section-head"><h2>我的收藏</h2><button class="text-btn" data-cat="收藏">查看全部</button></div>${favs.length?`<div class="card-scroll">${favs.map(card).join('')}</div>`:'<div class="list-card small">点击菜谱上的爱心，收藏想吃的菜。</div>'}<div class="section-head"><h2>用餐记录</h2></div>${state.meals.length?state.meals.slice().reverse().map(mealRow).join(''):'<div class="empty"><b>📅</b>还没有记录</div>'}</section>`}
function render(custom){const titles={home:'吃饭搭子',recipes:category==='烤鱼'?'烤鱼专区':'菜谱',vote:'双人投票',shopping:'买菜清单',mine:'我的餐桌'};$('#pageTitle').textContent=titles[page]||'菜谱详情';$('#app').innerHTML=custom||({home:home,recipes:recipesPage,vote:votePage,shopping:shoppingPage,mine:minePage}[page]());$$('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));bind()}
function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;go('recipes')});$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;render()});$$('[data-detail]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-fav]'))return;render(detail(b.dataset.detail))});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.fav,i=state.favorites.indexOf(id);i>=0?state.favorites.splice(i,1):state.favorites.push(id);save();toast(i>=0?'已取消收藏':'已收藏');render()});$$('[data-random]').forEach(b=>b.onclick=showRandom);const s=$('#searchInput');if(s)s.oninput=e=>{query=e.target.value;render();$('#searchInput').focus()};const back=$('[data-back]');if(back)back.onclick=()=>render();$$('[data-person]').forEach(b=>b.onclick=()=>{state.person=b.dataset.person;save();render()});$$('[data-vote]').forEach(b=>b.onclick=()=>{if(b.dataset.vote==='yes')state.votes[state.person].push(b.dataset.id);else state.votes[state.person].push('skip:'+b.dataset.id);save();render()});const reset=$('[data-reset-votes]');if(reset)reset.onclick=()=>{state.votes[state.person]=[];save();render()};$$('[data-add-shop]').forEach(b=>b.onclick=()=>addShopping(b.dataset.addShop));$$('[data-eaten]').forEach(b=>b.onclick=()=>recordMeal(b.dataset.eaten));$$('[data-check]').forEach(b=>b.onchange=()=>{state.shopping[+b.dataset.check].done=b.checked;save();render()});const clear=$('[data-clear-shop]');if(clear)clear.onclick=()=>{state.shopping=[];save();render()};$$('[data-delete-meal]').forEach(b=>b.onclick=()=>{state.meals=state.meals.filter(m=>m.uid!==b.dataset.deleteMeal);save();render()})}
function go(p){page=p;render();scrollTo({top:0,behavior:'smooth'})}
function addShopping(id){recipe(id).ingredients.forEach(([name,amount,cat])=>{const old=state.shopping.find(x=>x.name===name&&!x.done);if(old)old.amount+=' + '+amount;else state.shopping.push({name,amount,cat,done:false})});save();toast('已加入买菜清单')}
function recordMeal(id){state.meals.push({id,date:new Date().toISOString(),uid:crypto.randomUUID?.()||String(Date.now())});save();toast('已记录这顿饭')}
function showRandom(){const r=pickRandom();const match=state.votes.me.includes(r.id)&&state.votes.partner.includes(r.id);document.body.insertAdjacentHTML('beforeend',`<div class="random-overlay"><div class="random-sheet"><div class="big">${r.emoji}</div><div class="small">${match?'💞 双方都喜欢':'✨ 避开近期重复'}</div><h2>今天吃 ${r.name}</h2><p>${r.desc}</p><div class="vote-actions"><button class="btn-soft" data-again>再摇一次</button><button class="btn-primary" data-open-result>查看菜谱</button></div></div></div>`);$('[data-again]').onclick=()=>{$('.random-overlay').remove();showRandom()};$('[data-open-result]').onclick=()=>{$('.random-overlay').remove();render(detail(r.id))};$('.random-overlay').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.remove()}}
document.querySelector('.tabbar').onclick=e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)};
$('#todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});
$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else toast('请用浏览器菜单“添加到主屏幕”')};
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
render();
