const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY='foodie_pair_v1';
const defaultState={favorites:[],votes:{me:[],partner:[]},shopping:[],meals:[],person:'me'};
let state=Object.assign({},defaultState,JSON.parse(localStorage.getItem(KEY)||'{}'));
let page='home',category='全部',query='',deferredPrompt=null;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const recipe=id=>RECIPES.find(r=>r.id===id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=msg=>{const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
const weekStart=()=>{const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return d};
const recentIds=()=>state.meals.filter(m=>Date.now()-new Date(m.date).getTime()<7*864e5).map(m=>m.id);
function pickRandom(){const matches=state.votes.me.filter(x=>state.votes.partner.includes(x));const pool=matches.length?RECIPES.filter(r=>matches.includes(r.id)):RECIPES;const recent=recentIds();const weighted=pool.flatMap(r=>Array(recent.filter(x=>x===r.id).length?1:4).fill(r));return weighted[Math.floor(Math.random()*weighted.length)]}
function card(r){return `<article class="recipe-card" data-detail="${r.id}"><div class="food-art"><img src="${RECIPE_IMAGES[r.id]}" alt="${r.name}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span class="food-fallback" hidden>${r.emoji}</span><span class="menu-tag">${r.cat}</span><button class="fav-btn ${state.favorites.includes(r.id)?'on':''}" data-fav="${r.id}">${state.favorites.includes(r.id)?'♥':'♡'}</button></div><div class="card-body"><h3>${r.name}</h3><p>${r.desc}</p><div class="meta"><span>⏱ ${r.time}分钟</span><span>· ${r.difficulty}</span></div></div></article>`}
function home(){const suggestions=[...RECIPES].sort(()=>Math.random()-.5).slice(0,5),matches=state.votes.me.filter(x=>!x.startsWith('skip:')&&state.votes.partner.includes(x)).length,weekMeals=state.meals.filter(m=>new Date(m.date)>=weekStart()).length,notes=['好好吃饭，就是最温柔的陪伴。','今天的烦恼，交给一顿好吃的解决。','你负责可爱，我负责决定吃什么。','人间烟火气，最抚凡人心——尤其是两个人一起。','爱情要保鲜，晚饭也要换换口味。'],note=notes[new Date().getDate()%notes.length];return `<section class="page"><div class="love-note"><span>💌 今日悄悄话</span><b>${note}</b></div><div class="hero couple-hero"><span class="floating-heart h1">♡</span><span class="floating-heart h2">♥</span><small>彤彤和他的今日菜单</small><h2>今天吃什么呀？</h2><p>两个人投票，少一点纠结，多一点甜</p><button class="btn btn-light" data-random>🎀 帮我们决定</button></div><div class="couple-stats"><div><b>${matches}</b><span>默契菜品 💞</span></div><i></i><div><b>${weekMeals}</b><span>本周一起吃 🍽️</span></div></div><div class="section-head"><h2>约会小入口</h2></div><div class="quick-grid"><button class="quick" data-go="vote"><b>💗</b><span>默契投票</span></button><button class="quick" data-cat="烤鱼"><b>🐟</b><span>彤彤爱吃</span></button><button class="quick" data-go="shopping"><b>🛍️</b><span>一起买菜</span></button></div><div class="section-head"><h2>今日心动菜单</h2><button class="text-btn" data-random>换个口味</button></div><div class="card-scroll">${suggestions.map(card).join('')}</div><div class="section-head"><h2>我们的饭饭日记</h2><button class="text-btn" data-go="mine">全部记录</button></div>${state.meals.length?state.meals.slice(-2).reverse().map(mealRow).join(''):'<div class="list-card small pink-empty">第一次饭饭打卡，等你们一起完成 ♡</div>'}</section>`}
function recipesPage(){const cats=['全部','家常菜','烤鱼','火锅','汤羹','主食','泰餐','西餐','收藏'];let list=RECIPES.filter(r=>(category==='全部'||r.cat===category||(category==='收藏'&&state.favorites.includes(r.id)))&&r.name.includes(query)),empty=category==='收藏'?'<div class="empty favorite-empty" style="grid-column:1/-1"><b>💗</b>彤彤爱吃专区还是空的<br><span class="small">在首页或菜谱点击爱心，喜欢的菜就会出现在这里</span></div>':'<div class="empty" style="grid-column:1/-1"><b>🍽️</b>没有找到这道菜</div>';return `<section class="page">${category==='收藏'?'<div class="favorite-banner"><span>💖 专属收藏</span><b>彤彤爱吃的，都放在这里</b><small>点亮菜谱右上角的爱心即可添加</small></div>':''}<label class="search">⌕<input id="searchInput" placeholder="搜索菜名" value="${esc(query)}"></label><div class="chips">${cats.map(c=>`<button class="chip ${category===c?'active':''}" data-category="${c}">${c==='收藏'?'彤彤爱吃':c}</button>`).join('')}</div><div class="recipe-list">${list.length?list.map(card).join(''):empty}</div></section>`}
function detail(id){const r=recipe(id);return `<section class="page"><button class="text-btn" data-back>‹ 返回菜谱</button><div class="detail-hero photo"><img src="${RECIPE_IMAGES[r.id]}" alt="${r.name}"><div class="detail-caption"><div class="detail-emoji">${r.emoji}</div><h2>${r.name}</h2><p>${r.desc}</p><div class="pills"><span class="pill">${r.cat}</span><span class="pill">⏱ ${r.time}分钟</span><span class="pill">${r.difficulty}</span></div></div></div><div class="detail-section"><h3>准备食材 · 2人份</h3>${r.ingredients.map(i=>`<div class="ingredient-row"><span>${i[0]}</span><b>${i[1]}</b></div>`).join('')}<button class="btn btn-soft btn-block" style="margin-top:12px" data-add-shop="${r.id}">一键加入买菜清单</button></div><div class="detail-section"><h3>详细步骤</h3><ol class="steps">${r.steps.map(s=>`<li>${s}</li>`).join('')}</ol></div><button class="btn btn-primary btn-block" style="margin-top:14px" data-eaten="${r.id}">记录今天吃了这道菜</button></section>`}
function votePage(){const voted=state.votes[state.person],remaining=RECIPES.filter(r=>!voted.includes(r.id)&&!voted.includes('skip:'+r.id));const r=remaining[0];const matches=state.votes.me.filter(x=>!x.startsWith('skip:')&&state.votes.partner.includes(x));return `<section class="page vote-wrap"><div class="person-switch"><button data-person="me" class="${state.person==='me'?'active':''}">我的选择</button><button data-person="partner" class="${state.person==='partner'?'active':''}">搭子的选择</button></div>${matches.length?`<div class="match">🎉 已有 <b>${matches.length}</b> 道双方都喜欢，推荐时会优先出现</div>`:''}${r?`<div class="vote-card"><div class="vote-emoji">${r.emoji}</div><div class="small">${r.cat} · ${r.time}分钟</div><h2>${r.name}</h2><p class="small">${r.desc}</p><div class="vote-actions"><button class="nope" data-vote="no" data-id="${r.id}">跳过</button><button class="like" data-vote="yes" data-id="${r.id}">喜欢 ♡</button></div></div><p class="small">当前身份：${state.person==='me'?'我':'搭子'} · 已投 ${voted.length} 道</p>`:`<div class="empty"><b>🥳</b>这一轮投完啦<br><button class="btn btn-soft" style="margin-top:14px" data-reset-votes>重新投票</button></div>`}</section>`}
function shoppingPage(){const groups={};state.shopping.forEach((x,i)=>{(groups[x.cat]??=[]).push({...x,i})});return `<section class="page"><div class="row"><div class="grow"><h2 style="margin:4px 0">买菜清单</h2><p class="small">按食材类别自动整理</p></div>${state.shopping.length?'<button class="text-btn" data-clear-shop>清空</button>':''}</div>${state.shopping.length?Object.entries(groups).map(([g,items])=>`<div class="shopping-group"><h3>${g}</h3><div class="list-card">${items.map(x=>`<label class="check-row ${x.done?'done':''}"><input type="checkbox" data-check="${x.i}" ${x.done?'checked':''}><span class="grow">${x.name}</span><b>${x.amount}</b></label>`).join('')}</div></div>`).join(''):'<div class="empty"><b>🛒</b>清单还是空的<br><span class="small">打开菜谱，一键加入所需食材</span></div>'}</section>`}
function mealRow(m){const r=recipe(m.id);return `<div class="list-card row"><div style="font-size:34px">${r?.emoji||'🍽️'}</div><div class="grow"><h3>${r?.name||m.name}</h3><p class="small">${new Date(m.date).toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'short'})}</p></div><button class="text-btn" data-delete-meal="${m.uid}">删除</button></div>`}
function minePage(){const favs=RECIPES.filter(r=>state.favorites.includes(r.id));const week=state.meals.filter(m=>new Date(m.date)>=weekStart());const counts={};week.forEach(m=>{const c=m.cat||recipe(m.id)?.cat||'其他';counts[c]=(counts[c]||0)+1});const max=Math.max(1,...Object.values(counts));return `<section class="page"><div class="summary-grid"><div class="stat"><b>${favs.length}</b><span>我的收藏</span></div><div class="stat"><b>${week.length}</b><span>本周用餐</span></div><div class="stat"><b>${new Set(week.map(x=>x.id)).size}</b><span>不同菜品</span></div></div><div class="section-head"><h2>本周统计</h2></div><div class="list-card">${Object.keys(counts).length?Object.entries(counts).map(([c,n])=>`<div class="bar-row"><span>${c}</span><div class="bar"><i style="width:${n/max*100}%"></i></div><b>${n}</b></div>`).join(''):'<p class="small">本周还没有用餐记录。</p>'}</div><div class="section-head"><h2>我的收藏</h2><button class="text-btn" data-cat="收藏">查看全部</button></div>${favs.length?`<div class="card-scroll">${favs.map(card).join('')}</div>`:'<div class="list-card small">点击菜谱上的爱心，收藏想吃的菜。</div>'}<div class="section-head"><h2>用餐记录</h2></div>${state.meals.length?state.meals.slice().reverse().map(mealRow).join(''):'<div class="empty"><b>📅</b>还没有记录</div>'}</section>`}
const OUTINGS=[['火锅','🍲','热热闹闹，边涮边聊最适合约会'],['烤肉','🥩','今天不做饭，让滋滋冒油负责快乐'],['日料','🍣','精致一点，慢慢吃、慢慢说话'],['泰餐','🥭','酸酸辣辣，给平淡日子加点味道'],['西餐','🍷','偶尔正式一点，也很有仪式感'],['川菜','🌶️','一起辣到冒汗，也算共患难'],['粤菜','🥢','想吃清淡鲜美，就选这一顿'],['小龙虾','🦞','戴上手套以后，谁都别嫌谁狼狈'],['烧烤','🍢','吹着晚风撸串，是夏夜的浪漫'],['自助餐','🍰','意见不统一？那就每样都吃一点']];
function dineoutPage(){return `<section class="page"><div class="dineout-hero"><span>💑 今晚不下厨</span><h2>带彤彤下馆子</h2><p>做饭是生活，下馆子是约会。选不出来就交给缘分。</p><button class="btn btn-light" data-outing-random>🎲 随机选一家</button></div><div class="section-head"><h2>想吃哪一类？</h2></div><div class="outing-grid">${OUTINGS.map(o=>`<button class="outing-card" data-outing="${o[0]}"><b>${o[1]}</b><span>${o[0]}</span><small>${o[2]}</small></button>`).join('')}</div><div class="date-tip">💗 约会小提示：吃饭时把手机放下半小时，认真听对方说话，比选哪家店更重要。</div></section>`}
function render(custom){const recipeTitle=category==='收藏'?'彤彤爱吃专区':category==='烤鱼'?'烤鱼菜谱':'心动菜谱',titles={home:'彤彤今天吃什么！',recipes:recipeTitle,vote:'看看有多默契',shopping:'一起买菜',mine:'我们的饭饭日记',dineout:'今晚下馆子'};$('#pageTitle').textContent=titles[page]||'菜谱详情';$('#app').innerHTML=custom||({home:home,recipes:recipesPage,vote:votePage,shopping:shoppingPage,mine:minePage,dineout:dineoutPage}[page]());if(page==='home'){const favEntry=$('.quick[data-cat="烤鱼"]');favEntry.dataset.cat='收藏';favEntry.innerHTML='<b>💖</b><span>彤彤爱吃</span>';$('.quick-grid').insertAdjacentHTML('beforeend','<button class="quick" data-go="dineout"><b>👠</b><span>出去约会</span></button>')}$$('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));bind()}
function bind(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;go('recipes')});$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;render()});$$('[data-detail]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-fav]'))return;render(detail(b.dataset.detail))});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=b.dataset.fav,i=state.favorites.indexOf(id);i>=0?state.favorites.splice(i,1):state.favorites.push(id);save();toast(i>=0?'已取消收藏':'已收藏');render()});$$('[data-random]').forEach(b=>b.onclick=showRandom);const s=$('#searchInput');if(s)s.oninput=e=>{query=e.target.value;render();$('#searchInput').focus()};const back=$('[data-back]');if(back)back.onclick=()=>render();$$('[data-person]').forEach(b=>b.onclick=()=>{state.person=b.dataset.person;save();render()});$$('[data-vote]').forEach(b=>b.onclick=()=>{if(b.dataset.vote==='yes')state.votes[state.person].push(b.dataset.id);else state.votes[state.person].push('skip:'+b.dataset.id);save();render()});const reset=$('[data-reset-votes]');if(reset)reset.onclick=()=>{state.votes[state.person]=[];save();render()};$$('[data-add-shop]').forEach(b=>b.onclick=()=>addShopping(b.dataset.addShop));$$('[data-eaten]').forEach(b=>b.onclick=()=>recordMeal(b.dataset.eaten));$$('[data-check]').forEach(b=>b.onchange=()=>{state.shopping[+b.dataset.check].done=b.checked;save();render()});const clear=$('[data-clear-shop]');if(clear)clear.onclick=()=>{state.shopping=[];save();render()};$$('[data-delete-meal]').forEach(b=>b.onclick=()=>{state.meals=state.meals.filter(m=>m.uid!==b.dataset.deleteMeal);save();render()})}
function go(p){page=p;render();scrollTo({top:0,behavior:'smooth'})}
function addShopping(id){recipe(id).ingredients.forEach(([name,amount,cat])=>{const old=state.shopping.find(x=>x.name===name&&!x.done);if(old)old.amount+=' + '+amount;else state.shopping.push({name,amount,cat,done:false})});save();toast('已加入买菜清单')}
function recordMeal(id){state.meals.push({id,date:new Date().toISOString(),uid:crypto.randomUUID?.()||String(Date.now())});save();toast('已记录这顿饭')}
function showRandom(){const r=pickRandom();const match=state.votes.me.includes(r.id)&&state.votes.partner.includes(r.id);document.body.insertAdjacentHTML('beforeend',`<div class="random-overlay"><div class="random-sheet"><div class="big">${r.emoji}</div><div class="small">${match?'💞 双方都喜欢':'✨ 避开近期重复'}</div><h2>今天吃 ${r.name}</h2><p>${r.desc}</p><div class="vote-actions"><button class="btn-soft" data-again>再摇一次</button><button class="btn-primary" data-open-result>查看菜谱</button></div></div></div>`);$('[data-again]').onclick=()=>{$('.random-overlay').remove();showRandom()};$('[data-open-result]').onclick=()=>{$('.random-overlay').remove();render(detail(r.id))};$('.random-overlay').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.remove()}}
document.querySelector('.tabbar').onclick=e=>{const b=e.target.closest('[data-page]');if(b)go(b.dataset.page)};
document.addEventListener('click',e=>{const random=e.target.closest('[data-outing-random]'),choice=e.target.closest('[data-outing]');if(random)showOuting(OUTINGS[Math.floor(Math.random()*OUTINGS.length)]);if(choice)showOuting(OUTINGS.find(o=>o[0]===choice.dataset.outing))});
function showOuting(o){document.body.insertAdjacentHTML('beforeend',`<div class="random-overlay"><div class="random-sheet outing-sheet"><div class="big">${o[1]}</div><div class="small">今晚约会答案是</div><h2>去吃${o[0]}！</h2><p>${o[2]}</p><div class="outing-actions"><button class="btn-soft" data-outing-close>换一个</button><button class="btn-soft" data-find-outing>找附近餐厅</button><button class="btn-primary" data-outing-picked>选好了 ✓</button></div></div></div>`);$('[data-outing-close]').onclick=()=>{$('.random-overlay').remove();showOuting(OUTINGS[Math.floor(Math.random()*OUTINGS.length)])};$('[data-find-outing]').onclick=()=>window.open('https://uri.amap.com/search?keyword='+encodeURIComponent('附近'+o[0]),'_blank');$('[data-outing-picked]').onclick=()=>{state.meals.push({id:'outing:'+o[0],name:'下馆子 · '+o[0],cat:'下馆子',date:new Date().toISOString(),uid:crypto.randomUUID?.()||String(Date.now())});save();$('.random-overlay').remove();toast('已记进我们的饭饭日记 💗')};$('.random-overlay').onclick=e=>{if(e.target===e.currentTarget)e.currentTarget.remove()}}
$('#todayLabel').textContent=new Date().toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});
$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else toast('请用浏览器菜单“添加到主屏幕”')};
if('serviceWorker'in navigator)window.addEventListener('load',async()=>{const reg=await navigator.serviceWorker.register('./sw.js?v=8',{updateViaCache:'none'});reg.update()});
render();
